### ISSUE TITLE
The `print_graph` function should read one graph at a time and output image

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/grodecoder#13]
To be able to use the `print_graph` function either with one large graph, either with individual molecular graph, this function should read one and only one graph.
It could also output a png image saved on disk instead of an image (possibly embedded in a Jupyter notebook).

@KarinDuong could you please handle this?

**Comment by KarinDuong** [comment]
Done ! But I don't understand this part "(possibly embedded in a Jupyter notebook)" : do you want me to save the PNG in a Jupyter NoteBook ?

**Comment by pierrepo** [comment]
No, just output graph as png images.

**Comment by KarinDuong** [comment]
Ok, I already did that in my recent commit
