### ISSUE TITLE
Add water model tip5pe, tip4pew and spce

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/grodecoder#28]
- https://github.com/gromacs/gromacs/blob/main/share/top/oplsaa.ff/tip5pe.itp
- https://github.com/gromacs/gromacs/blob/main/share/top/oplsaa.ff/tip4pew.itp
- https://github.com/gromacs/gromacs/blob/main/share/top/oplsaa.ff/spce.itp

**Comment by KarinDuong** [comment]
@pierrepo but it's already added to SOLVANTS_LIST (file : mol_def.py)

SOLVANTS_LIST = [{"name": "solvant water TIP3P", "res_name": "TIP3", "atom_names": ["OH2"]}, 
                 {"name": "solvant water TIP3P", "res_name": "SOL", "atom_names": ["OW", "HW1", "HW2"]},  # TIP3
                 {"name": "solvant water TIP4P", "res_name": "SOL", "atom_names": ["OW", "HW1", "HW2", "MW"]},  # TIP4
                 {"name": "solvant water TIP5P", "res_name": "SOL", "atom_names": ["OW", "HW1", "HW2", "LP1", "LP2"]},  # TIP5
                 {"name": "solvant urea", "res_name": "URE", "atom_names": ["C", "O", "N1", "H11", "H12", "N2", "H21", "H22"]},
                 ]

**Comment by pierrepo** [comment]
@KarinDuong please be explicit if models are identical based on their residue and atom names by expanding the `name` field.

For instance : `solvant water TIP3P` -> `solvant water TIP3P/spc/spce`
