### ISSUE TITLE
Add organic solvants

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/grodecoder#32]
- https://github.com/gromacs/gromacs/blob/main/share/top/oplsaa.ff/methanol.itp
- https://github.com/gromacs/gromacs/blob/main/share/top/oplsaa.ff/ethanol.itp
- https://github.com/gromacs/gromacs/blob/main/share/top/oplsaa.ff/1propanol.itp

**Comment by pierrepo** [comment]
Verify also with other force fields:

- https://github.com/gromacs/gromacs/blob/main/share/top/gromos43a1.ff/methanol.itp
- https://github.com/gromacs/gromacs/blob/main/share/top/gromos43a1.ff/methanol.itp
- ...

**Comment by pierrepo** [comment]
Could you also check for ethanol and 1propanol for the Gromos43a1 force field?

**Comment by pierrepo** [comment]
oups, that may not exist...

**Comment by KarinDuong** [comment]
@pierrepo There are only methanol in the repo "gromos43a1.ff" (and nothing in the other repo gromos)
