### ISSUE TITLE
Add structure description

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/grodecoder#35]
From this code:

https://github.com/pierrepo/grodecoder/blob/92e38acd10bbd9ee118b1f6f2255877cfe837a2a/fasta_seq_into_PDBID.py#L73-L76

Could you also get the name (type ?) of the macromolecule? You may need to modify a little bit your query to the PDB API.

**Comment by KarinDuong** [comment]
@pierrepo I search this option in the doc (https://search.rcsb.org/index.html#return-count) but I can't find it

**Comment by pierrepo** [comment]
OK. I'll take a look. Please leave this issue open.

**Comment by pierrepo** [comment]
And go home!

**Comment by pierrepo** [comment]
You probably need an extra step to get info about all PDB IDs you got.
This could be useful:
- https://www.rcsb.org/docs/programmatic-access/web-services-overview#data-api
- https://data.rcsb.org/index.html#data-api
