### ISSUE TITLE
Create a system with methionine rich protein and methanol

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/grodecoder#39]
Create a system with:

- a methionine-rich protein: [2MAT](https://www.rcsb.org/structure/2MAT)
- water (TIP3)
- ions (Na+, Cl-, K+, Mg2+, OH-)
- methanol, ethanol and urea (why not)

**Comment by KarinDuong** [comment]
I can add 2MAT + methanol, ethanol and urea with PACKMOL. But I can't add ions and water with it

**Comment by KarinDuong** [comment]
Done ! And it work, Grodecoder find the correct composition :tada:
