### ISSUE TITLE
Improve molecular inventory export

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/grodecoder#45]
In the `export_inventory()` function:

```
res_names = " ".join(set(sorted(nx.get_node_attributes(graph, "residue_name").values())))
```

Get the full sequence of residues, not unique residues (with `set()`)

In the final dictionary (`final_dict` variable), also add the checksum of the input file: 

```
final_dict = {"inventory": list_dict_molecule, 
              "resolution": resolution, 
              "date": str(datetime.datetime.today()), 
              "file_name": filename,
              "file_md5sum" : XXX
             }
```

Also, save the json file in the current directory (not in the directory of the input file) with the date and time in the name. For instance: `grodecoder_2024-05-21_11-07-00.json`

**Comment by KarinDuong** [comment]
What do you mean by "checksum of the input file" ?
