### ISSUE TITLE
Improve JSON export

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/grodecoder#46]
@KarinDuong the JSON export looks really great :tada: 

Here are a couple of improvements:

## JSON file name

The actual name of the JSON file is something like `barstar_2024-05-23_07:34.json`, could you make it like `2024-05-23_07-34-23_barstar.json`?
- The date is first in the format `YYYY-MM-DD_HH-MM-SS`
- The name of the file comes last.

## Filename field

When running this command:

```bash
python grodecoder.py --input data/examples/barstar.gro
```

The `filename` field in the JSON contains only the filename.

Could you rename the `filename` field into `file_path` and get the full relative path? For instance:

```python
"file_path": "data/examples/barstar.gro"
```

## Date field

Also the date field in currently:

```python
"date": "2024-05-23_07:34"
```

could you make it like this:

```python
"date": "YYYY-MM-DD HH-MM-SS"
```

For instance:

```python
"date": "2024-05-23 07-47-13"
```

## Residue ids

Could you try to export the residue ids (intervals) for each molecule in the JSON?

I'm not sure about the appropriate format. You could try something like this:

```python
"residue_ids": "34-56 67 83 88-102 106-184 189-212"
```

**Comment by pierrepo** [comment]
Bonus question: did you find a nice JSON viewer in VS Code?

**Comment by pierrepo** [comment]
One last thing, could you try filling the `formula_no_h` field?

**Comment by KarinDuong** [comment]
> Bonus question: did you find a nice JSON viewer in VS Code?

I forgot to add indentation to the function json.dump(). Now it should be prettier, and it can be open with VS without specific viewer (imo)
