### ISSUE TITLE
Create a new `molecular_type` field in the molecular inventory

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/grodecoder#59]
The `molecular_type` field should replace all the followings: `is_protein`, `is_lipid`, `is_ion`, `is_solvant`.

Default value for `molecular_type` could be `unknown`. Possible values could be `protein`, `ion`, `solvant` or `lipid`.

**Comment by pierrepo** [comment]
I re-opened this issue.
@KarinDuong could you make a PR an update tests?

**Comment by KarinDuong** [comment]
Can we also close this issue ?
